name: SonarQube
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: windows-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.sonar/cache
            ~/.nuget/packages
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/sonar-project.properties') }}
          restore-keys: ${{ runner.os }}-sonar-

      - name: Install SonarScanner
        run: |
          dotnet tool install dotnet-sonarscanner --tool-path .\.sonar\scanner --version 5.9.0 #Specify version for consistency
          echo "::set-env name=SONAR_SCANNER_PATH::$(Get-Item -Path .\.sonar\scanner\dotnet-sonarscanner.dll | Resolve-Path)"

      - name: Build and Analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_SCANNER_PATH: ${{ env.SONAR_SCANNER_PATH }} #Use the environment variable
        run: |
          $SonarScannerPath = "$ENV:SONAR_SCANNER_PATH"
          if (-not (Test-Path -Path $SonarScannerPath)) {
            Write-Error "SonarScanner not found at: $SonarScannerPath.  Check installation."
            exit 1
          }

          & "$SonarScannerPath" begin /k:"LuongQuocKhang_Exchange" /o:"exchange" /d:sonar.token="$ENV:SONAR_TOKEN" /d:sonar.host.url="https://sonarcloud.io"
          cd Exchange
          dotnet build || exit 1 #Exit if build fails
          & "$SonarScannerPath" end /d:sonar.token="$ENV:SONAR_TOKEN" || exit 1 #Exit if end fails